# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/384f0212-50fa-4d1c-bb84-721566a93375";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0233-A15F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/london/windows" =
    { device = "/dev/disk/by-uuid/86883E6D883E5C3D";
      fsType = "ntfs3";
    };

  fileSystems."/home/london/games" =
    { device = "/dev/disk/by-uuid/082ba09d-4db9-4842-82bc-637c15c95fce";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  fileSystems."/home/london/wingames" =
    { device = "/dev/disk/by-uuid/6F986C930DE2F134";
      fsType = "ntfs3";
    };

  fileSystems."/home/london/jellyfin" =
    { device = "/dev/disk/by-uuid/2ced34d3-a928-4fcf-8d74-7d436cd333b2";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
